package blog;
/*
 * 웹에서 블로그 생성버튼을 누르면 naver/webcontent에 개인 블로그페이지 jsp파일이 만들어지는데
 * 그 안에 삽입될 코드들을 만들어 놓은 템플릿입니다.
 * 수정할 때 찾기 -> "cjsgoddns" 키워드를 id로 바꾸면 됩니다. ex) 28라인 참조바람.
 * */
public class BlogTemplate {
	
	public BlogTemplate() {
		
	}
	//블로그 템플릿
	public String blogTemplate(String id) {

		String blogTemplate = 
				"<%@page import=\"blog.UtilMgr\"%>\r\n"
				+ "<%@page import=\"blog.BlogPostBean\"%>\r\n"
				+ "<%@page import=\"blog.CateBean\"%>\r\n"
				+ "<%@page import=\"java.util.Vector\"%>\r\n"
				+ "<%@ page contentType=\"text/html; charset=EUC-KR\"%>\r\n"
				+ "<%request.setCharacterEncoding(\"EUC-KR\");%>\r\n"
				+ "<jsp:useBean id=\"blogBean\" class=\"blog.BlogBean\"/>\r\n"
				+ "<jsp:useBean id=\"blogMgr\" class=\"blog.BlogMgr\"/>\r\n"
				+ "<jsp:useBean id=\"cateBean\" class=\"blog.CateBean\"/>\r\n"
				+ "<jsp:useBean id=\"cateMgr\" class=\"blog.CateMgr\"/>\r\n"
				+ "<jsp:useBean id=\"postMgr\" class=\"blog.BlogPostMgr\"/>\r\n"
				+ "<%\r\n"
				+ "		String id = \""+id+"\";\r\n"
				+ "		blogBean = blogMgr.getBlogPage(id);\r\n"
				+ "		String blogBanner = blogBean.getBannerImg();\r\n"
				+ "		String blogProfileDesc = blogBean.getProfileDesc();\r\n"
				+ "		String blogProfileImg = blogBean.getProfileImage();\r\n"
				+ "		String sid = (String) session.getAttribute(\"id\");\r\n"
				+ "		\r\n"
				+ "		//아무 값도 전달받지 못하고 넘어온 경우 웰컴페이지(해당id페이지의 최신글)를 띄우기 위해 변수값 설정////////////////////////\r\n"
				+ "		BlogPostBean wBean = postMgr.getWelcomeSet(id);\r\n"
				+ "		String wTitle = wBean.getPostTitle();\r\n"
				+ "		String wText = wBean.getPostText();\r\n"
				+ "		String wImg = wBean.getPostImg();\r\n"
				+ "		String wTopic = wBean.getPostTopic();\r\n"
				+ "		String wDate = wBean.getPostDate();\r\n"
				+ "		\r\n"
				+ "		String wCNum = Integer.toString(wBean.getPostCNum());\r\n"
				+ "		String wLike = Integer.toString(wBean.getPostLike());\r\n"
				+ "		String wPostNum = Integer.toString(wBean.getPostNo());\r\n"
				+ "		String wView = Integer.toString(wBean.getPostView());\r\n"
				+ "		//////////////////////////////////////////////////////////////////////////\r\n"
				+ "		//쿼리 조건에 넣기 위한 변수 값 전달받거나 웰컴값 강제대입////////////////////////////////////\r\n"
				+ "		int cateNum;\r\n"
				+ "		int postNum;\r\n"
				+ "		//카테고리 번호 cateNum\r\n"
				+ "		String reqCateNum = request.getParameter(\"cateNum\");\r\n"
				+ "		if(reqCateNum==null||reqCateNum.equals(\"\")) //전달받지 못해서 null일 경우 위에서 설정한 값으로 강제하기\r\n"
				+ "			reqCateNum = wCNum;		\r\n"
				+ "		cateNum = Integer.parseInt(reqCateNum);//전달받았거나 강제로 설정된 reqCateNum을 int 변환\r\n"
				+ "		//포스트 번호 postNum\r\n"
				+ "		String reqPostNum = request.getParameter(\"postNum\");\r\n"
				+ "		if(reqPostNum==null||reqPostNum.equals(\"\"))\r\n"
				+ "			reqPostNum = wPostNum;\r\n"
				+ "		postNum = Integer.parseInt(reqPostNum);\r\n"
				+ "		//카테고리 이름 cateName\r\n"
				+ "		String cateName = request.getParameter(\"category\");\r\n"
				+ "		if(cateName==null||cateName.equals(\"\"))\r\n"
				+ "			cateName = cateMgr.getCateName(id, cateNum);\r\n"
				+ "		//////////////////////////////////////////////////////////////////////////\r\n"
				+ "		//페이징 처리를 위한 설정///////////////////////////////////////////////////////////\r\n"
				+ "		int totalRecord = 0;//총 게시물 수\r\n"
				+ "		int numPerPage = 5;//페이지당 레코드 개수(5, 10, 15, 30)\r\n"
				+ "		int pagePerBlock = 15;//블럭당 페이지 개수\r\n"
				+ "		int totalPage = 0;//총 페이지 개수\r\n"
				+ "		int totalBlock = 0;//총 블럭 개수\r\n"
				+ "		int nowPage = 1;//현재 페이지\r\n"
				+ "		int nowBlock = 1;//현재 블럭\r\n"
				+ "		\r\n"
				+ "		//요청된 numPerPage 처리를 위해\r\n"
				+ "		if(request.getParameter(\"numPerPage\") != null){\r\n"
				+ "			numPerPage = UtilMgr.parseInt(request, \"numPerPage\");\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		//총 게시물 수\r\n"
				+ "		totalRecord = postMgr.getTotalCount(cateNum, id);\r\n"
				+ "		\r\n"
				+ "		if(request.getParameter(\"nowPage\")!=null){\r\n"
				+ "			nowPage = UtilMgr.parseInt(request, \"nowPage\");\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "		//sql문에 들어가는 start, cnt 선언\r\n"
				+ "		int start = (nowPage*numPerPage)-numPerPage;\r\n"
				+ "		int cnt = numPerPage;\r\n"
				+ "		\r\n"
				+ "		//전체페이지 개수\r\n"
				+ "		totalPage = (int)Math.ceil((double)totalRecord/numPerPage);\r\n"
				+ "		//전체블럭 개수\r\n"
				+ "		totalBlock = (int)Math.ceil((double)totalPage/pagePerBlock);\r\n"
				+ "		//현재블럭\r\n"
				+ "		nowBlock = (int)Math.ceil((double)nowPage/pagePerBlock);\r\n"
				+ "%>\r\n"
				+ "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "	<meta charset=\"EUC-KR\">\r\n"
				+ "	<title><%=id %>님의 블로그</title>\r\n"
				+ "	<link rel=\"stylesheet\" href=\"./resources/css/blog_style.css\">\r\n"
				+ "	<script type=\"text/javascript\" src=\"./resources/js/script.js\"></script>\r\n"
				+ "	<script type=\"text/javascript\">\r\n"
				+ "		function numPerFn(numPerPage) {\r\n"
				+ "			//alert(numPerPage);\r\n"
				+ "			document.readFrm.numPerPage.value = numPerPage;\r\n"
				+ "			document.readFrm.submit();\r\n"
				+ "		}\r\n"
				+ "		function pageing(page) {\r\n"
				+ "			document.readFrm.nowPage.value=page;\r\n"
				+ "			document.readFrm.submit();\r\n"
				+ "		}\r\n"
				+ "		function block(block) {\r\n"
				+ "			document.readFrm.nowPage.value=<%=pagePerBlock%>*(block-1)+1;\r\n"
				+ "			document.readFrm.submit();\r\n"
				+ "		}\r\n"
				+ "		function read(num) {\r\n"
				+ "			document.readFrm.postNum.value = num;\r\n"
				+ "			document.readFrm.action = \"blog_<%=id%>.jsp\";\r\n"
				+ "			document.readFrm.submit();\r\n"
				+ "		}\r\n"
				+ "		\r\n"
				+ "	</script>\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "	<div id=\"root\">\r\n"
				+ "		\r\n"
				+ "		<div id=\"blog-navBarWrap\">\r\n"
				+ "			<div class=\"blog-navbar\">\r\n"
				+ "				<div class=\"blog-navbar-left\">\r\n"
				+ "					<a href=\"../chu/index.jsp\" style=\"width: 81px; height: 26px; margin-left: 18%;\">\r\n"
				+ "						<img src=\"./resources/img/logo-md.png\" alt=\"img\">\r\n"
				+ "					</a> \r\n"
				+ "				</div>\r\n"
				+ "				<div class=\"blog-navbar-right\">\r\n"
				+ "					<%if(sid!=null&&!sid.equals(\"\")){ %>\r\n"
				+ "					<div><a href=\"../member/logout.jsp\">로그아웃</a></div>\r\n"
				+ "						<%if(sid!=id&&!sid.equals(id)){ %>\r\n"
				+ "					<div><a href=\"blog_<%=sid%>.jsp\">내 블로그</a></div>\r\n"
				+ "						<%} %>\r\n"
				+ "					<%}else{ %> \r\n"
				+ "					<div><a href=\"../member/login.jsp\">로그인</a></div>\r\n"
				+ "					<%} %>\r\n"
				+ "				</div>\r\n"
				+ "			</div>\r\n"
				+ "		</div>\r\n"
				+ "		<div id=\"mainImgWrap\">\r\n"
				+ "			<div style=\"height: 100%;\">\r\n"
				+ "				<img class=\"bannerImg\" src=\"./data/<%=blogBanner %>\">\r\n"
				+ "			</div>\r\n"
				+ "		</div>\r\n"
				+ "		\r\n"
				+ "		<div id=\"container\">\r\n"
				+ "		\r\n"
				+ "			<div class=\"blog-conLeft\">\r\n"
				+ "				\r\n"
				+ "				<div class=\"blog-profileWrap\">\r\n"
				+ "					<div class=\"blog-profileImg\">\r\n"
				+ "						<div style=\"width: 100%; height: 100%;\">\r\n"
				+ "							<img src=\"./data/<%=blogProfileImg %>\" style=\"width: 100%; height: 100%;\">\r\n"
				+ "						</div>\r\n"
				+ "					</div>\r\n"
				+ "					<div class=\"blog-profileId\">\r\n"
				+ "						<div><strong><%=id %>님의 블로그</strong></div>\r\n"
				+ "					</div>\r\n"
				+ "					<div class=\"blog-profileDesc\">\r\n"
				+ "						<div><%=blogProfileDesc %></div>\r\n"
				+ "					</div>\r\n"
				+ "				</div>\r\n"
				+ "				<%if(sid!=null&&sid.equals(id)){ %>\r\n"
				+ "				<div style=\"margin-top: 5px;\">\r\n"
				+ "					<a href=\"blog_<%=id%>_posting.jsp\">글쓰기 </a><small style=\"padding: 5px;\"> / </small>\r\n"
				+ "					<a href=\"blog_<%=id%>_setting.jsp\"> 설정</a>\r\n"
				+ "				</div>\r\n"
				+ "				<%} %>\r\n"
				+ "				<div class=\"blog-postCategorys\">					\r\n"
				+ "					\r\n"
				+ "						<div>\r\n"
				+ "							<div class=\"pCategory\"><strong>카테고리</strong></div>\r\n"
				+ "							<%\r\n"
				+ "									Vector<CateBean> cateVlist = new Vector<CateBean>();\r\n"
				+ "									cateVlist = cateMgr.getBlogCategory(id);\r\n"
				+ "									for(int i=0; i<cateVlist.size(); i++){\r\n"
				+ "										cateBean = cateVlist.get(i);\r\n"
				+ "										String cName = cateBean.getBlogCateName();\r\n"
				+ "										int cNum = cateBean.getBlogCateNum();\r\n"
				+ "										int pNum = postMgr.getCateNewPostNum(id, cNum);\r\n"
				+ "							%>\r\n"
				+ "							\r\n"
				+ "							<div class=\"pCategory\">\r\n"
				+ "							<form class=\"categoryFrm\">\r\n"
				+ "								<input type=\"submit\" class=\"textbtn\" name=\"category\" value=\"<%=cName%>\">\r\n"
				+ "								<input type=\"hidden\" name=\"cateNum\" value=\"<%=cNum%>\">\r\n"
				+ "								<input type=\"hidden\" name=\"postNum\" value=\"<%=pNum%>\">\r\n"
				+ "							</form>\r\n"
				+ "							</div>\r\n"
				+ "							\r\n"
				+ "							<%	} %>\r\n"
				+ "								\r\n"
				+ "						</div>\r\n"
				+ "					\r\n"
				+ "				</div>\r\n"
				+ "				\r\n"
				+ "			</div>\r\n"
				+ "			\r\n"
				+ "			\r\n"
				+ "			<div class=\"blog-conRight\">\r\n"
				+ "			<%\r\n"
				+ "					Vector<BlogPostBean> postVlist = new Vector<BlogPostBean>();\r\n"
				+ "					//String cNum = request.getParameter(\"cateNum\");\r\n"
				+ "					\r\n"
				+ "					String postTitle=\"\";\r\n"
				+ "					String postText=\"\";\r\n"
				+ "					String postDate=\"\";\r\n"
				+ "					int postLike=0;\r\n"
				+ "					int postView=0;\r\n"
				+ "					\r\n"
				+ "					/*  if(cNum==null)\r\n"
				+ "						cNum=\"1\";\r\n"
				+ "					cateNum = Integer.parseInt(cNum); \r\n"
				+ "					if(postNum==0){\r\n"
				+ "						BlogPostBean postBean = postMgr.getCateNewPost(id, cateNum);\r\n"
				+ "						postTitle = postBean.getPostTitle();\r\n"
				+ "						postText = postBean.getPostText();\r\n"
				+ "						postDate = postBean.getPostDate();\r\n"
				+ "						postLike = postBean.getPostLike(); \r\n"
				+ "						postView = postBean.getPostView();\r\n"
				+ "					}else{		 */\r\n"
				+ "						\r\n"
				+ "					BlogPostBean postBean = postMgr.getCateInNumPost(id, cateNum, postNum);\r\n"
				+ "					postTitle = postBean.getPostTitle();\r\n"
				+ "					postText = postBean.getPostText();\r\n"
				+ "					postDate = postBean.getPostDate();\r\n"
				+ "					postLike = postBean.getPostLike(); \r\n"
				+ "					postView = postBean.getPostView();\r\n"
				+ "					\r\n"
				+ "			%>\r\n"
				+ "				<div class=\"postWrap\">\r\n"
				+ "					<div class=\"postTitle\">\r\n"
				+ "						<span class=\"postSpan-lg\">제목: <%=postTitle %></span>\r\n"
				+ "					</div>\r\n"
				+ "					<%if(sid!=null&&sid.equals(id)){ %>\r\n"
				+ "					<div style=\"display: flex; flex-direction: row; justify-content: flex-end; align-items: self-end;\">\r\n"
				+ "					<form action=\"blog_<%=id %>_modify.jsp\" method=\"post\">\r\n"
				+ "						<input type=\"submit\" value=\"수정하기\">\r\n"
				+ "						<input type=\"hidden\" name=\"postTitle\" value=\"<%=postTitle %>\">\r\n"
				+ "						<input type=\"hidden\" name=\"postText\" value=\"<%=postText %>\">\r\n"
				+ "					</form>\r\n"
				+ "					</div>\r\n"
				+ "					<%} %>\r\n"
				+ "					<div class=\"postContents\">\r\n"
				+ "						<%=postText %>\r\n"
				+ "					</div>\r\n"
				+ "					<div class=\"postLike\">\r\n"
				+ "						<span class=\"postSpan-sm\">좋아요: <%=postLike %></span>\r\n"
				+ "					</div>\r\n"
				+ "					<div class=\"postDate\">\r\n"
				+ "						<span class=\"postSpan-sm\">게시일: <%=postDate %></span>\r\n"
				+ "					</div>\r\n"
				+ "				</div>\r\n"
				+ "				\r\n"
				+ "				<div class=\"postListWrap\">\r\n"
				+ "					<div class=\"postListTop\">\r\n"
				+ "						<div>\r\n"
				+ "							<% %>\r\n"
				+ "							<strong><%=cateName %> <%=totalRecord %>개의 글</strong>\r\n"
				+ "						</div>\r\n"
				+ "						<form name=\"npFrm\" method=\"post\">\r\n"
				+ "							<select name=\"numPerPage\" onchange=\"numPerFn(this.form.numPerPage.value)\">\r\n"
				+ "								<option value=\"5\" selected>5줄 보기</option>\r\n"
				+ "								<option value=\"10\">10줄 보기</option>\r\n"
				+ "								<option value=\"15\">15줄 보기</option>\r\n"
				+ "							</select>\r\n"
				+ "						</form>\r\n"
				+ "						<script>document.npFrm.numPerPage.value=<%=numPerPage%>;</script>\r\n"
				+ "					</div>\r\n"
				+ "					<div class=\"postListBottom\">\r\n"
				+ "						<table style=\"width: 95%;\">\r\n"
				+ "							<thead>\r\n"
				+ "								<tr>\r\n"
				+ "									<td style=\"width:80%\"><strong>제목</strong></td>\r\n"
				+ "									<td style=\"width:10%\"><strong>작성일</strong></td>\r\n"
				+ "									<td style=\"width:10%\"><strong>조회수</strong></td>\r\n"
				+ "								<tr>\r\n"
				+ "							</thead>\r\n"
				+ "							<tbody>\r\n"
				+ "							<%\r\n"
				+ "									postVlist = postMgr.getPostList(id, cateNum, start, cnt);\r\n"
				+ "									for(int i=0; i<postVlist.size(); i++){\r\n"
				+ "										BlogPostBean bean = postVlist.get(i);\r\n"
				+ "										String title = bean.getPostTitle();\r\n"
				+ "										String date = bean.getPostDate();\r\n"
				+ "										postNum = bean.getPostNo();\r\n"
				+ "										int view = bean.getPostView();\r\n"
				+ "							%> \r\n"
				+ "								<tr>\r\n"
				+ "									<td style=\" width:80%\">\r\n"
				+ "										<a href=\"javascript:read('<%=postNum%>')\">\r\n"
				+ "										<%=title %>\r\n"
				+ "										</a>\r\n"
				+ "									</td>\r\n"
				+ "									<td style=\"width:10%\"><%=date %></td>\r\n"
				+ "									<td style=\"width:10%\" align=\"center\"><%=view %></td>\r\n"
				+ "								<tr>\r\n"
				+ "							<%	} %>\r\n"
				+ "								<tr>\r\n"
				+ "									<td align=\"center\">\r\n"
				+ "									<!-- 페이징 및 블럭 Start -->\r\n"
				+ "									<!-- 이전 블럭 -->\r\n"
				+ "										<%if(nowBlock>1){ %>\r\n"
				+ "										<button onclick=\"javascript:block('<%=nowBlock-1 %>')\">&lt;</button>\r\n"
				+ "										<%} %>\r\n"
				+ "										<!-- 페이징 -->\r\n"
				+ "										<%\r\n"
				+ "												int pageStart = (nowBlock-1)*pagePerBlock+1;\r\n"
				+ "												int pageEnd = (pageStart+pagePerBlock)<=totalPage ? pageStart+pagePerBlock : totalPage+1;\r\n"
				+ "												for(; pageStart<pageEnd;pageStart++){\r\n"
				+ "										%>\r\n"
				+ "										<a href=\"javascript: pageing('<%=pageStart%>')\">\r\n"
				+ "											<%if(nowPage==pageStart){%><font color=\"blue\"><%} %>\r\n"
				+ "											[<%=pageStart %>]\r\n"
				+ "											<%if(nowPage==pageStart){%></font><%} %>\r\n"
				+ "										</a>\r\n"
				+ "										<%	}//for%>\r\n"
				+ "										<!-- 다음 블럭 -->\r\n"
				+ "										<%if(totalBlock>nowBlock){ %>\r\n"
				+ "										<button onclick=\"javascript:block('<%=nowBlock+1 %>')\">></button>\r\n"
				+ "										<%} %>\r\n"
				+ "									<!-- 페이징 및 블럭 End -->\r\n"
				+ "									</td>\r\n"
				+ "								</tr>\r\n"
				+ "							</tbody>\r\n"
				+ "						</table>\r\n"
				+ "					</div>\r\n"
				+ "				</div>\r\n"
				+ "			</div>			\r\n"
				+ "		</div>\r\n"
				+ "		<form name=\"readFrm\">\r\n"
				+ "			<input type=\"hidden\" name=\"nowPage\" value=\"<%=nowPage%>\">\r\n"
				+ "			<input type=\"hidden\" name=\"numPerPage\" value=\"<%=numPerPage%>\">\r\n"
				+ "			<input type=\"hidden\" name=\"cateNum\" value=\"<%=cateNum%>\">\r\n"
				+ "			<input type=\"hidden\" name=\"category\" value=\"<%=cateName%>\">\r\n"
				+ "			<input type=\"hidden\" name=\"postNum\">\r\n"
				+ "		</form>\r\n"
				+ "	</div>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		return blogTemplate;
	}
	
	//블로그 웰컴 템플릿
	public String blogWelcomeTemplate(String id) {
		
		String blogWelcomeTemplate = 
				"";
		return blogWelcomeTemplate;
	}
	
	//블로그 세팅 템플릿
	public String blogSettingTemplate(String id) {
		String blogSettingTemplate = 
				"";
		return blogSettingTemplate;
	}
	//블로그 포스팅 템플릿
	public String blogPostingTemplate(String id) {
		String blogPostingTemplate = 
				"";
		return blogPostingTemplate;
	}
}